# platform :ios, '12.4'

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '15.1'
prepare_react_native_project!
use_modular_headers!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'frontend' do
  config = use_native_modules!

  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Analytics'
  pod 'GoogleUtilities'


  use_react_native!(
    :path => config[:reactNativePath],
    :fabric_enabled => false, # true이면 Fabric 아키텍처 사용
    :hermes_enabled => false,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'frontendTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # 기본 React Native 후처리
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    # ✅ Swift experimental feature 플래그 추가
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['OTHER_SWIFT_FLAGS'] ||= ['']
        config.build_settings['OTHER_SWIFT_FLAGS'] << '-enable-experimental-feature' << 'AccessLevelOnImport'
      end
    end
  end
end
